FROM node:22-alpine

RUN apk add --no-cache libc6-compat

RUN mkdir -p /home/node/app && chown -R node:node /home/node

USER node

WORKDIR /home/node/app

COPY . .

EXPOSE 3000

CMD ["yarn", "dev"]